apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goapp-ingress
  namespace: goapp
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: goapp
            port:
              number: 8080