apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple
  namespace: observability
spec:
  strategy: allInOne
  allInOne:
    options:
      log-level: debug
  storage:
    type: memory