apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: goapp
images:
- name: goapp
  newName: matias1210/argocd-estudos
  newTag: 4234723131eb52b82fcaa22bd33d7af4e7f9ddd8
