apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: goapp
images:
- name: goapp
  newName: matias1210/argocd-estudos
  newTag: 94e707cc08429dfbdafe45b081239300f9f1ff9b
