apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: goapp
images:
- name: goapp
  newName: matias1210/argocd-estudos
  newTag: 32c7b2b7691bab4b8bb5a66e6590153845a13a4a
